echo "      execSync('sudo service tor stop');  // Stop Tor after closing the browser" >> continuous_visit_puppeteer.js
          echo "      console.log('Tor stopped after visiting the website.');" >> continuous_visit_puppeteer.js
          echo "    } catch (error) {" >> continuous_visit_puppeteer.js
          echo "      console.error('Failed to visit website:', error.message);" >> continuous_visit_puppeteer.js
          echo "      if (browser) await browser.close();" >> continuous_visit_puppeteer.js
          echo "      await restartTor(); // Restart Tor if navigation fails" >> continuous_visit_puppeteer.js
          echo "    }" >> continuous_visit_puppeteer.js
          echo "  }" >> continuous_visit_puppeteer.js
          echo "}" >> continuous_visit_puppeteer.js
          echo "" >> continuous_visit_puppeteer.js
          echo "async function randomWait() {" >> continuous_visit_puppeteer.js
          echo "  const waitTime = Math.floor(Math.random() * (5 - 2 + 1) + 2) * 60 * 1000;  // Random wait between 2 to 5 minutes" >> continuous_visit_puppeteer.js
          echo "  console.log('Waiting for', waitTime / 60000, 'minutes before next visit...');" >> continuous_visit_puppeteer.js
          echo "  await new Promise(resolve => setTimeout(resolve, waitTime));" >> continuous_visit_puppeteer.js
          echo "}" >> continuous_visit_puppeteer.js
          echo "" >> continuous_visit_puppeteer.js
          echo "async function fetchIPsAndVisit() {" >> continuous_visit_puppeteer.js
          echo "  await fetchIP(false);  // Fetch IP without Tor" >> continuous_visit_puppeteer.js
          echo "  await fetchIPWithTorRetry();  // Fetch IP with Tor, retry until successful" >> continuous_visit_puppeteer.js
          echo "  while (true) {" >> continuous_visit_puppeteer.js
          echo "    execSync('sudo service tor start');  // Start Tor before each visit" >> continuous_visit_puppeteer.js
          echo "    console.log('Tor started before visiting the website.');" >> continuous_visit_puppeteer.js
          echo "" >> continuous_visit_puppeteer.js
          echo "    await fetchIP(true);  // Show public IP after starting Tor" >> continuous_visit_puppeteer.js
          echo "    await visitWebsite('https://dileepa2.netlify.app');" >> continuous_visit_puppeteer.js
          echo "    await randomWait();" >> continuous_visit_puppeteer.js
          echo "  }" >> continuous_visit_puppeteer.js
          echo "}" >> continuous_visit_puppeteer.js
          echo "" >> continuous_visit_puppeteer.js
          echo "fetchIPsAndVisit();" >> continuous_visit_puppeteer.js
          
      - name: Run Puppeteer Script
        run: node continuous_visit_puppeteer.js
